# Generated by Django 3.1.6 on 2023-07-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videoblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='videoblog/')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.FileField(upload_to='videoblog/')),
            ],
            options={
                'db_table': 'web_videoblog',
                'ordering': ['-id'],
            },
        ),
    ]
