# Generated by Django 3.1.6 on 2023-07-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('blog post', 'Blog Post'), ('webinar', 'Webinar'), ('report', 'Report')], default='blog post', max_length=20)),
            ],
            options={
                'db_table': 'web_blog',
                'ordering': ['-id'],
            },
        ),
    ]
