# Generated by Django 3.1.6 on 2023-07-25 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='white_logo',
            field=models.FileField(blank=True, null=True, upload_to='customers/'),
        ),
    ]
