# Generated by Django 3.1.6 on 2023-07-26 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20230726_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='background_color',
            field=models.CharField(default='color', max_length=255),
            preserve_default=False,
        ),
    ]
